#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

#define XPAR_XBRAM_NUM_INSTANCES 2

/* Definitions for peripheral AXI_BRAM_CTRL_0 */
#define XPAR_AXI_BRAM_CTRL_0_COMPATIBLE "xlnx,axi-bram-ctrl-4.1"
#define XPAR_AXI_BRAM_CTRL_0_BASEADDR 0xc0000000
#define XPAR_AXI_BRAM_CTRL_0_HIGHADDR 0xc0001fff
#define XPAR_AXI_BRAM_CTRL_0_DATA_WIDTH 0x20
#define XPAR_AXI_BRAM_CTRL_0_ECC 0x0
#define XPAR_AXI_BRAM_CTRL_0_FAULT_INJECT 0x0
#define XPAR_AXI_BRAM_CTRL_0_CE_FAILING_REGISTERS 0x0
#define XPAR_AXI_BRAM_CTRL_0_BRAM_CORRECTABLE_FAILING_DATA_REGS 0x0
#define XPAR_AXI_BRAM_CTRL_0_UE_FAILING_REGISTERS 0x0
#define XPAR_AXI_BRAM_CTRL_0_BRAM_UNCORRECTABLE_FAILING_DATA_REGS 0x0
#define XPAR_AXI_BRAM_CTRL_0_BRAM_ECC_STATUS_INTERRUPT_PRESENT 0x0
#define XPAR_AXI_BRAM_CTRL_0_BRAM_CORRECTABLE_COUNTER_BITS 0x0
#define XPAR_AXI_BRAM_CTRL_0_ECC_ONOFF_REGISTER 0x0
#define XPAR_AXI_BRAM_CTRL_0_ECC_ONOFF_RESET_VALUE 0x0
#define XPAR_AXI_BRAM_CTRL_0_WRITE_ACCESS 0x0
#define XPAR_AXI_BRAM_CTRL_0_BRAM_MEM_BASE_ADDRESS 0x0
#define XPAR_AXI_BRAM_CTRL_0_BRAM_MEM_HIGH_ADDRESS 0x0
#define XPAR_AXI_BRAM_CTRL_0_MEM_CTRL_BASE_ADDRESS 0x0
#define XPAR_AXI_BRAM_CTRL_0_MEM_CTRL_HIGH_ADDRESS 0x0

/* Canonical definitions for peripheral AXI_BRAM_CTRL_0 */
#define XPAR_XBRAM_0_BASEADDR 0xc0000000
#define XPAR_XBRAM_0_HIGHADDR 0xc0001fff
#define XPAR_XBRAM_0_BRAM_CORRECTABLE_FAILING_DATA_REGS 0x0
#define XPAR_XBRAM_0_BRAM_UNCORRECTABLE_FAILING_DATA_REGS 0x0
#define XPAR_XBRAM_0_BRAM_ECC_STATUS_INTERRUPT_PRESENT 0x0
#define XPAR_XBRAM_0_BRAM_CORRECTABLE_COUNTER_BITS 0x0
#define XPAR_XBRAM_0_BRAM_MEM_BASE_ADDRESS 0x0
#define XPAR_XBRAM_0_BRAM_MEM_HIGH_ADDRESS 0x0
#define XPAR_XBRAM_0_COMPATIBLE "xlnx,axi-bram-ctrl-4.1"
#define XPAR_XBRAM_0_CE_FAILING_REGISTERS 0x0
#define XPAR_XBRAM_0_DATA_WIDTH 0x20
#define XPAR_XBRAM_0_ECC 0x0
#define XPAR_XBRAM_0_ECC_ONOFF_REGISTER 0x0
#define XPAR_XBRAM_0_ECC_ONOFF_RESET_VALUE 0x0
#define XPAR_XBRAM_0_FAULT_INJECT 0x0
#define XPAR_XBRAM_0_MEM_CTRL_BASE_ADDRESS 0x0
#define XPAR_XBRAM_0_MEM_CTRL_HIGH_ADDRESS 0x0
#define XPAR_XBRAM_0_UE_FAILING_REGISTERS 0x0
#define XPAR_XBRAM_0_WRITE_ACCESS 0x0

/* Definitions for peripheral AXI_BRAM_CTRL_1 */
#define XPAR_AXI_BRAM_CTRL_1_COMPATIBLE "xlnx,axi-bram-ctrl-4.1"
#define XPAR_AXI_BRAM_CTRL_1_BASEADDR 0xc2000000
#define XPAR_AXI_BRAM_CTRL_1_HIGHADDR 0xc2001fff
#define XPAR_AXI_BRAM_CTRL_1_DATA_WIDTH 0x20
#define XPAR_AXI_BRAM_CTRL_1_ECC 0x0
#define XPAR_AXI_BRAM_CTRL_1_FAULT_INJECT 0x0
#define XPAR_AXI_BRAM_CTRL_1_CE_FAILING_REGISTERS 0x0
#define XPAR_AXI_BRAM_CTRL_1_BRAM_CORRECTABLE_FAILING_DATA_REGS 0x0
#define XPAR_AXI_BRAM_CTRL_1_UE_FAILING_REGISTERS 0x0
#define XPAR_AXI_BRAM_CTRL_1_BRAM_UNCORRECTABLE_FAILING_DATA_REGS 0x0
#define XPAR_AXI_BRAM_CTRL_1_BRAM_ECC_STATUS_INTERRUPT_PRESENT 0x0
#define XPAR_AXI_BRAM_CTRL_1_BRAM_CORRECTABLE_COUNTER_BITS 0x0
#define XPAR_AXI_BRAM_CTRL_1_ECC_ONOFF_REGISTER 0x0
#define XPAR_AXI_BRAM_CTRL_1_ECC_ONOFF_RESET_VALUE 0x0
#define XPAR_AXI_BRAM_CTRL_1_WRITE_ACCESS 0x0
#define XPAR_AXI_BRAM_CTRL_1_BRAM_MEM_BASE_ADDRESS 0x0
#define XPAR_AXI_BRAM_CTRL_1_BRAM_MEM_HIGH_ADDRESS 0x0
#define XPAR_AXI_BRAM_CTRL_1_MEM_CTRL_BASE_ADDRESS 0x0
#define XPAR_AXI_BRAM_CTRL_1_MEM_CTRL_HIGH_ADDRESS 0x0

/* Canonical definitions for peripheral AXI_BRAM_CTRL_1 */
#define XPAR_XBRAM_1_BASEADDR 0xc2000000
#define XPAR_XBRAM_1_HIGHADDR 0xc2001fff
#define XPAR_XBRAM_1_BRAM_CORRECTABLE_FAILING_DATA_REGS 0x0
#define XPAR_XBRAM_1_BRAM_UNCORRECTABLE_FAILING_DATA_REGS 0x0
#define XPAR_XBRAM_1_BRAM_ECC_STATUS_INTERRUPT_PRESENT 0x0
#define XPAR_XBRAM_1_BRAM_CORRECTABLE_COUNTER_BITS 0x0
#define XPAR_XBRAM_1_BRAM_MEM_BASE_ADDRESS 0x0
#define XPAR_XBRAM_1_BRAM_MEM_HIGH_ADDRESS 0x0
#define XPAR_XBRAM_1_COMPATIBLE "xlnx,axi-bram-ctrl-4.1"
#define XPAR_XBRAM_1_CE_FAILING_REGISTERS 0x0
#define XPAR_XBRAM_1_DATA_WIDTH 0x20
#define XPAR_XBRAM_1_ECC 0x0
#define XPAR_XBRAM_1_ECC_ONOFF_REGISTER 0x0
#define XPAR_XBRAM_1_ECC_ONOFF_RESET_VALUE 0x0
#define XPAR_XBRAM_1_FAULT_INJECT 0x0
#define XPAR_XBRAM_1_MEM_CTRL_BASE_ADDRESS 0x0
#define XPAR_XBRAM_1_MEM_CTRL_HIGH_ADDRESS 0x0
#define XPAR_XBRAM_1_UE_FAILING_REGISTERS 0x0
#define XPAR_XBRAM_1_WRITE_ACCESS 0x0

#define XPAR_XUARTNS550_NUM_INSTANCES 1

/* Definitions for peripheral AXI_UART16550_0 */
#define XPAR_AXI_UART16550_0_COMPATIBLE "xlnx,axi-uart16550-2.0"
#define XPAR_AXI_UART16550_0_BASEADDR 0x44a10000
#define XPAR_AXI_UART16550_0_HIGHADDR 0x44a1ffff
#define XPAR_AXI_UART16550_0_CLOCK_FREQ 0x5f5e100
#define XPAR_AXI_UART16550_0_CURRENT_SPEED 0x0

/* Canonical definitions for peripheral AXI_UART16550_0 */
#define XPAR_XUARTNS550_0_BASEADDR 0x44a10000
#define XPAR_XUARTNS550_0_HIGHADDR 0x44a1ffff
#define XPAR_XUARTNS550_0_COMPATIBLE "xlnx,axi-uart16550-2.0"
#define XPAR_XUARTNS550_0_CLOCK_FREQ 0x5f5e100
#define XPAR_XUARTNS550_0_CURRENT_SPEED 0x0

/* Definitions for peripheral MNIST_ACCEL_0 */
#define XPAR_MNIST_ACCEL_0_BASEADDR 0x44a00000
#define XPAR_MNIST_ACCEL_0_HIGHADDR 0x44a0ffff

/* Canonical definitions for peripheral MNIST_ACCEL_0 */
#define XPAR_MNIST_ACCEL_0_BASEADDR 0x44a00000
#define XPAR_MNIST_ACCEL_0_HIGHADDR 0x44a0ffff

/*  BOARD definition */
#define XPS_BOARD_BASYS3

#define XPAR_AXI_BRAM_0_BASEADDRESS 0xc0000000
#define XPAR_AXI_BRAM_0_HIGHADDRESS 0xc0001fff
#define XPAR_AXI_BRAM_1_BASEADDRESS 0xc2000000
#define XPAR_AXI_BRAM_1_HIGHADDRESS 0xc2001fff
#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 100000000

#define XPAR_MICROBLAZE_ADDR_SIZE 32

#define XPAR_MICROBLAZE_USE_STACK_PROTECTION 0

/* Number of SLRs */
#define NUMBER_OF_SLRS 0x1

/* Device ID */
#define XPAR_DEVICE_ID "7a35t"

#endif  /* end of protection macro */