# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/mnist_pin_assignment.xdc

# Block Designs: bd/fpga_mnist/fpga_mnist.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_mnist || ORIG_REF_NAME==fpga_mnist} -quiet] -quiet

# IP: bd/fpga_mnist/ip/fpga_mnist_microblaze_0_0/fpga_mnist_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_mnist_microblaze_0_0 || ORIG_REF_NAME==fpga_mnist_microblaze_0_0} -quiet] -quiet

# IP: bd/fpga_mnist/ip/fpga_mnist_axi_uartlite_0_0/fpga_mnist_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_mnist_axi_uartlite_0_0 || ORIG_REF_NAME==fpga_mnist_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/fpga_mnist/ip/fpga_mnist_mnist_accel_0_0/fpga_mnist_mnist_accel_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_mnist_mnist_accel_0_0 || ORIG_REF_NAME==fpga_mnist_mnist_accel_0_0} -quiet] -quiet

# IP: bd/fpga_mnist/ip/fpga_mnist_lmb_bram_if_cntlr_0_0/fpga_mnist_lmb_bram_if_cntlr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_mnist_lmb_bram_if_cntlr_0_0 || ORIG_REF_NAME==fpga_mnist_lmb_bram_if_cntlr_0_0} -quiet] -quiet

# IP: bd/fpga_mnist/ip/fpga_mnist_lmb_bram_if_cntlr_1_0/fpga_mnist_lmb_bram_if_cntlr_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_mnist_lmb_bram_if_cntlr_1_0 || ORIG_REF_NAME==fpga_mnist_lmb_bram_if_cntlr_1_0} -quiet] -quiet

# IP: bd/fpga_mnist/ip/fpga_mnist_clk_wiz_0_0/fpga_mnist_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_mnist_clk_wiz_0_0 || ORIG_REF_NAME==fpga_mnist_clk_wiz_0_0} -quiet] -quiet

# IP: bd/fpga_mnist/ip/fpga_mnist_proc_sys_reset_0_0/fpga_mnist_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_mnist_proc_sys_reset_0_0 || ORIG_REF_NAME==fpga_mnist_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/fpga_mnist/ip/fpga_mnist_axi_smc_0/fpga_mnist_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_mnist_axi_smc_0 || ORIG_REF_NAME==fpga_mnist_axi_smc_0} -quiet] -quiet

# IP: bd/fpga_mnist/ip/fpga_mnist_blk_mem_gen_0_0/fpga_mnist_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_mnist_blk_mem_gen_0_0 || ORIG_REF_NAME==fpga_mnist_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/fpga_mnist/ip/fpga_mnist_blk_mem_gen_1_0/fpga_mnist_blk_mem_gen_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_mnist_blk_mem_gen_1_0 || ORIG_REF_NAME==fpga_mnist_blk_mem_gen_1_0} -quiet] -quiet

# IP: bd/fpga_mnist/ip/fpga_mnist_mdm_0_0/fpga_mnist_mdm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_mnist_mdm_0_0 || ORIG_REF_NAME==fpga_mnist_mdm_0_0} -quiet] -quiet

# XDC: c:/vitis_mnist/mnist_fpga/mnist_fpga.gen/sources_1/bd/fpga_mnist/fpga_mnist_ooc.xdc
