# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/vitis_mnist/mnist_fpga/mnist_fpga.srcs/constrs_1/new/mnist_pin_assignment.xdc

# Block Designs: C:/vitis_mnist/mnist_fpga/mnist_fpga.srcs/sources_1/bd/fpga_mnist/fpga_mnist.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_mnist || ORIG_REF_NAME==fpga_mnist} -quiet] -quiet

# IP: C:/vitis_mnist/mnist_fpga/mnist_fpga.srcs/sources_1/bd/fpga_mnist/ip/fpga_mnist_microblaze_0_0/fpga_mnist_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_mnist_microblaze_0_0 || ORIG_REF_NAME==fpga_mnist_microblaze_0_0} -quiet] -quiet

# IP: C:/vitis_mnist/mnist_fpga/mnist_fpga.srcs/sources_1/bd/fpga_mnist/ip/fpga_mnist_clk_wiz_0_0/fpga_mnist_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_mnist_clk_wiz_0_0 || ORIG_REF_NAME==fpga_mnist_clk_wiz_0_0} -quiet] -quiet

# IP: C:/vitis_mnist/mnist_fpga/mnist_fpga.srcs/sources_1/bd/fpga_mnist/ip/fpga_mnist_proc_sys_reset_0_0/fpga_mnist_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_mnist_proc_sys_reset_0_0 || ORIG_REF_NAME==fpga_mnist_proc_sys_reset_0_0} -quiet] -quiet

# IP: C:/vitis_mnist/mnist_fpga/mnist_fpga.srcs/sources_1/bd/fpga_mnist/ip/fpga_mnist_axi_smc_0/fpga_mnist_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_mnist_axi_smc_0 || ORIG_REF_NAME==fpga_mnist_axi_smc_0} -quiet] -quiet

# IP: C:/vitis_mnist/mnist_fpga/mnist_fpga.srcs/sources_1/bd/fpga_mnist/ip/fpga_mnist_blk_mem_gen_1_0/fpga_mnist_blk_mem_gen_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_mnist_blk_mem_gen_1_0 || ORIG_REF_NAME==fpga_mnist_blk_mem_gen_1_0} -quiet] -quiet

# IP: C:/vitis_mnist/mnist_fpga/mnist_fpga.srcs/sources_1/bd/fpga_mnist/ip/fpga_mnist_mdm_0_0/fpga_mnist_mdm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_mnist_mdm_0_0 || ORIG_REF_NAME==fpga_mnist_mdm_0_0} -quiet] -quiet

# IP: C:/vitis_mnist/mnist_fpga/mnist_fpga.srcs/sources_1/bd/fpga_mnist/ip/fpga_mnist_axi_bram_ctrl_0_0/fpga_mnist_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_mnist_axi_bram_ctrl_0_0 || ORIG_REF_NAME==fpga_mnist_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: C:/vitis_mnist/mnist_fpga/mnist_fpga.srcs/sources_1/bd/fpga_mnist/ip/fpga_mnist_blk_mem_gen_0_4/fpga_mnist_blk_mem_gen_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_mnist_blk_mem_gen_0_4 || ORIG_REF_NAME==fpga_mnist_blk_mem_gen_0_4} -quiet] -quiet

# IP: C:/vitis_mnist/mnist_fpga/mnist_fpga.srcs/sources_1/bd/fpga_mnist/ip/fpga_mnist_axi_bram_ctrl_1_0/fpga_mnist_axi_bram_ctrl_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_mnist_axi_bram_ctrl_1_0 || ORIG_REF_NAME==fpga_mnist_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: C:/vitis_mnist/mnist_fpga/mnist_fpga.srcs/sources_1/bd/fpga_mnist/ip/fpga_mnist_ila_0_0/fpga_mnist_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_mnist_ila_0_0 || ORIG_REF_NAME==fpga_mnist_ila_0_0} -quiet] -quiet

# IP: C:/vitis_mnist/mnist_fpga/mnist_fpga.srcs/sources_1/bd/fpga_mnist/ip/fpga_mnist_mnist_accel_0_2/fpga_mnist_mnist_accel_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_mnist_mnist_accel_0_2 || ORIG_REF_NAME==fpga_mnist_mnist_accel_0_2} -quiet] -quiet

# IP: C:/vitis_mnist/mnist_fpga/mnist_fpga.srcs/sources_1/bd/fpga_mnist/ip/fpga_mnist_axi_uart16550_0_1/fpga_mnist_axi_uart16550_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_mnist_axi_uart16550_0_1 || ORIG_REF_NAME==fpga_mnist_axi_uart16550_0_1} -quiet] -quiet

# XDC: c:/vitis_mnist/mnist_fpga/mnist_fpga.gen/sources_1/bd/fpga_mnist/fpga_mnist_ooc.xdc
